#!/bin/bash

name=`whoami`

I=`dpkg -s vim | grep "Status" ` #проверяем состояние пакета (dpkg) и ищем в выводе его статус (grep)
if [[ -z "$I" ]] #проверяем что нашли строку со статусом (что строка не пуста)
then
    echo "Please install Vim " #выводим результат
    exit 2
fi

host=`hostname`

`cp bashrc.template .bashrc`
`cp vimrc.template vimrc`
echo "Creating .bashrc   ......OK"
echo "Creating vimrc     ......OK"

`sed -i "9s/WHOAMI/$name/" .bashrc`
`sed -i "21s/HNAME/$host/" .bashrc`

`sudo rm /home/$name/.bashrc`
`sudo rm /etc/vim/vimrc`

`sudo cp .bashrc /home/$name/.bashrc`
`sudo cp vimrc /etc/vim/vimrc`

`rm .bashrc`
`rm vimrc`

echo "Done! Reboot you system"
