#!/bin/bash

name=`whoami`
host=`hostname`

I=`dpkg -s vim 2>/dev/null | grep "Status" ` #проверяем состояние пакета (dpkg) и ищем в выводе его статус (grep)
if [[ -z "$I" ]] #проверяем что нашли строку со статусом (что строка не пуста)
then
    echo "Installing Vim..." #выводим результат
    `sudo apt-get install vim -y 2>&1 1>/dev/null`
    echo "Vim installed!"
fi

`cp bashrc.template .bashrc`
`cp vimrc.template vimrc`
`cp screenrc.template screenrc`

echo "Creating .bashrc    ......OK"
echo "Creating vimrc      ......OK"
echo "Creating .screenrc  ......OK"

`sed -i "9s/WHOAMI/$name/" .bashrc`
`sed -i "21s/HNAME/$host/" .bashrc`

`sudo rm /home/$name/.bashrc`
`sudo rm /home/$name/.screenrc`
`sudo rm /etc/vim/vimrc`

`sudo cp .bashrc /home/$name/.bashrc`
`sudo cp .screenrc /home/$name/.screenrc`
`sudo cp vimrc /etc/vim/vimrc`

`rm .bashrc`
`rm vimrc`
`rm .screenrc`

echo "Done! Reboot you system"
